import localFont from "next/font/local";
import "./globals.css";
import "./styles/global.scss";

import { Inter, Plus_Jakarta_Sans } from "next/font/google";

export const metadata = {
	title: "Phil",
	description: "Generated by create next app",
};

const inter = Inter({
	subsets: ["latin"],
	variable: true,
});

const plusJakartaSans = Plus_Jakarta_Sans({
	subsets: ["latin"],
	weight: ["400", "700"], // Use 'weight' instead of 'weights'
});

const fraunces = localFont({
	src: [
		{
			path: "./fonts/Fraunces/Fraunces_144pt-Thin.ttf",
			weight: "200",
			style: "normal",
		},
		{
			path: "./fonts/Fraunces/Fraunces_144pt-Bold.ttf",
			weight: "700",
			style: "normal",
		},
		{
			path: "./fonts/Fraunces/Fraunces_144pt-SemiBold.ttf",
			weight: "600",
			style: "normal",
		},
		{
			path: "./fonts/Fraunces/Fraunces_144pt-Regular.ttf",
			weight: "400",
			style: "normal",
		},
		{
			path: "./fonts/Fraunces/Fraunces_144pt-Light.ttf",
			weight: "300",
			style: "normal",
		},
	],
});

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} ${plusJakartaSans.className} ${fraunces.className}`}
			>
				{children}
			</body>
		</html>
	);
}
